"""add_employees_is_active

Revision ID: ad656eccfbb1
Revises: cbefd961ed2e
Create Date: 2026-05-09 04:38:48.577365

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad656eccfbb1'
down_revision: str | Sequence[str] | None = 'cbefd961ed2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_active')
    # ### end Alembic commands ###
