"""Add role

Revision ID: d6c43585aa92
Revises: 73835ae26b70
Create Date: 2026-05-09 13:35:19.291806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c43585aa92'
down_revision: Union[str, Sequence[str], None] = '73835ae26b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'HR', 'ADMIN', name='role'), nullable=False, server_default='EMPLOYEE'))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=False, server_default='false'))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
